import Head from 'next/head'

import { BsFillMoonStarsFill } from 'react-icons/bs'
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import code from '../public/code.png'
import advicegenerator from '../public/advicegenerator.png'
import caravan from '../public/caravan.png'
import NLW from '../public/NLW e-sports.png'
import todoappReact from '../public/todoappReact.png'
import TextSpeech from '../public/Text-Speech.png'
import qrcode from '../public/qrcode generator.png'
import ecommerce from '../public/e-commercejquery.png'
import introsection from '../public/introsection.png'
import interactiveC from '../public/interactiveC.png'
import wildbeast from '../public/wildbeast.png'
import dragDrop from '../public/drag and drop.png'
import countriesapi from '../public/countries-api.png'

import { useState, useEffect } from 'react'

export default function Home() {
  const [darkMode, setDarkMode] = useState(true)
  const [language, setLanguage] = useState(true)

  useEffect(() => {
    const key = Object.keys(localStorage)
    if (key.includes('theme')) {
      setDarkMode(JSON.parse(localStorage.getItem('theme')))
    }
  }, [])

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">Dev Leonardo</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    window.localStorage.setItem('theme', !darkMode)
                    setDarkMode(JSON.parse(localStorage.getItem('theme')))
                  }}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <span
                  onClick={() => setLanguage(!language)}
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 cursor-pointer rounded ml-8"
                >
                  {language ? 'English' : 'Português'}
                </span>
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1aWwubNFxswb77chC_XdAqVFUsVe_yL4A/view"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded ml-8"
                >
                  {language ? 'Currículo' : 'Resume'}
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Leonardo de Lima
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              {language ? 'Front-end Developer' : 'Software Engineer'}
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              {language
                ? 'Olá, sou desenvolvedor front-end junior. Navegue pela página para conhecer mais sobre mim e meus projetos!'
                : "Hello, I'm a junior front-end developer. Browse the page to learn more about me and my projects!"}
            </p>
          </div>
          <div className="text-5xl flex  justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a
              href="https://github.com/LeonardoLimaSilveira"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub className="cursor-pointer" />
            </a>
            <a
              href="https://www.linkedin.com/in/leonardo-lima-42596b235/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
          </div>
          <div className="relative mx-auto  bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
            <Image
              alt="image description"
              src={deved}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
        <section>
          <div className=" ">
            <div className="text-center flex justify-center items-center flex-col shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <Image alt="image description" src={code} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">
                {language ? 'Experiência' : 'Experience'}
              </h3>
              <p className="py-2 dark:text-gray-200">
                {language
                  ? 'Desenvolvedor Front-end Junior com conhecimentos em HTML, CSS, JS, REACTJS, REACT ROUTER, JQUERY, GIT, TAILWINDCSS, BOOTSTRAP, TYPESCRIPT, STYLED-COMPONENTS'
                  : 'SE with knowledge in HTML, CSS, JS, REACTJS, REACT ROUTER, JQUERY, GIT, TAILWINDCSS, BOOTSTRAP, TYPESCRIPT, STYLED-COMPONENTS'}
              </p>
              <p className="text-gray-800 py-1 dark:text-gray-200">
                {' '}
                {language
                  ? 'Busco usar todos os meus conhecimentos em prol da empresa e colaboradores, tentando sempre estar evoluindo e atualizado naquilo que os nossos clientes precisam.'
                  : 'I seek to use all my knowledge for the benefit of the company and collaborators, always trying to be evolving and updated on what our customers need.'}
              </p>
            </div>
          </div>
        </section>
        <section className="">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">
              {language ? 'Portifólio' : 'Portfolio'}
            </h3>
            <p className="dark:text-white my-2">
              {language
                ? 'Aqui abaixo estão alguns de meus projetos'
                : 'Below you will find some of my projects.'}
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  ">
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://todoappfacebook-o5fp15bss-leonardolimasilveira.vercel.app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={todoappReact}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 REACTJS
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://interactivecardreact-p2k54mngl-leonardolimasilveira.vercel.app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={interactiveC}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 REACTJS
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://introsec-mo0wu4ves-leonardolimasilveira.vercel.app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={introsection}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 REACTJS
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://countries-api-green.vercel.app"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={countriesapi}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 REACTJS
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/E-commerceByLeonardoLS"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={ecommerce}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT JQUERY
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/Caravan-bootstap"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={caravan}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT BOOTSTRAP
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://github.com/LeonardoLimaSilveira/e-Sports"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={NLW}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 REACTJS NODEJS PRISMA MySQL REACTNATIVE
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/Text-speech"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={TextSpeech}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/QRCODEGenerator/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={qrcode}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/AdviceGenerator"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={advicegenerator}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/wildbeast"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={wildbeast}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 CSS GRID
              </span>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a
                href="https://leonardolimasilveira.github.io/drag-and-drop"
                target="_blank"
                rel="noopener noreferrer"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={'100%'}
                  height={'100%'}
                  layout="responsive"
                  src={dragDrop}
                />
              </a>
              <span className="dark:text-gray-400 my-3 flex justify-center">
                HTML5 CSS3 JAVASCRIPT
              </span>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
